id = "tonel-smalltalk"
name = "Tonel Smalltalk"
version = "0.3.0"
schema_version = 1
authors = ["Masashi Umezawa <ume@softumeya.com>"]
description = "Tonel Smalltalk language support."
repository = "https://github.com/mumez/zed-extension-tonel-smalltalk"

[grammars.tonel_smalltalk]
repository = "https://github.com/mumez/tree-sitter-tonel-smalltalk"
commit = "bf7b534f559237aa098fb08985c3ad3259ad5878"

[language_servers.tonel-smalltalk-language-server]
name = "tonel-smalltalk-language-server"
language = "Tonel Smalltalk"
