id = "tonel-smalltalk"
name = "Tonel Smalltalk"
version = "0.1.6"
schema_version = 1
authors = ["mumez"]
description = "Tonel Smalltalk language support for Zed: syntax highlighting and go-to-definition"
repository = "https://github.com/mumez/zed-extension-tonel-smalltalk"

[grammars.tonel_smalltalk]
repository = "https://github.com/mumez/tree-sitter-tonel-smalltalk"
commit = "382bfaf5a74d7b7497075b34a51d2d739612cac2"

[language_servers.tonel-smalltalk-language-server]
name = "tonel-smalltalk-language-server"
language = "Tonel Smalltalk"
